import './globals.scss'

export const metadata = {
  title: 'Fizjoterapią Joanna Ejsmont',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>{children}</body>
    </html>
  )
}
